### ISSUE TITLE
Disable Grub startup timeout

### ISSUE THREAD

**Issue by Erriez** [eaksel/packer-Debian10#11]
Grub boot menu is started by default with a timeout value of 5 seconds. This can be changed to value 0 and is useful to speed-up the boot process for running automated tests. Probably nobody uses Grub boot menu in a VM.

**scripts/setup.yml**

```yaml
  - name: Disable quiet boot mode and set timeout
    lineinfile:
      path: /etc/default/grub
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - {regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"', line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'}
      - {regexp: 'GRUB_TIMEOUT="5"', line: 'GRUB_TIMEOUT="0"'}
```

![Screenshot from 2021-09-01 23-16-57](https://user-images.githubusercontent.com/8849873/131746410-67f3ad0d-fb1b-4970-8985-d12187cc953f.png)

@eaksel Do you like this idea? Do you want me to create a PR?

PS: Sorry to bother you with PR's, this is a very useful project. :-)
